name: CICD Workshop workflow
on: 
  release: 
    type: [published]
jobs: 
  docker:
    runs-on: ubuntu-latest
    steps:
      #https://github.com/marketplace/actions/build-and-push-docker-images 
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: e0008064/randnum:${{ github.ref_name }} #need to change this to take current tag 

      #https://github.com/marketplace/actions/slack-send
      -
        name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          channel-id: '#sa54-test-submission'
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Name: ${{ env.Name }}\nMatriculation: ${{ env.M_Num }}\nEmail: ${{ env.Email }}\nRepo: ${{ env.Repo }}\nImage name: ${{ env.Image_Name }}\nImage url: ${{ env.Image_URL }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          Name: Cheong Li Yuan
          M_Num: A0144049H
          Email: e0008064@u.nus.edu
          Repo: git://github.com:cheongliyuan/DipSA-CICD-Workshop.git
          Image_Name: e0008064/randnum:${{ github.ref_name }} 
          Image_URL: https://hub.docker.com/repository/docker/e0008064/randnum 