name: CICD Workshop workflow
on: 
  push:
  #release: #setting to push for 
    #type: [created]
jobs: 
  docker:
    runs-on: ubuntu-latest
    steps:
      #https://github.com/marketplace/actions/build-and-push-docker-images #temp skipping docker
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1 
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: e0008064/cicdworkshop:v0.2 #need to change this to take current tag 

      #https://github.com/marketplace/actions/slack-send
      -
        name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          channel-id: '#sa54-test-submission'
          payload: |
            {

              "text": "Where does this showup? GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Name: ${{ env.Name }}\nMatriculation: ${{ env.M_Num }}\nEmail: ${{ env.Email }}\nRepo: ${{ env.Repo }}\nImage name: \nImage url: "
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          Name: Cheong Li Yuan
          M_Num: A0144049H
          Email: e0008064@u.nus.edu
          Repo: git://github.com:cheongliyuan/DipSA-CICD-Workshop.git
          Image_Name: 
          Image_URL: 
          
          